### ISSUE TITLE
Layout per worspace

### ISSUE THREAD

**Issue by Ghorin46** [micahosborne/gSnap#12]
This is a very interesting extension ! Thank you for your work.
Now i have a suggestion : to be able to use a different layout for each worspace. That would be useful for people (like me) who use a different worspace for different activities. On some workspace I will have only one application (in full screen), on another one I will have two (with a vertical split), on another one I will have 3 (two on the right with a vertical split, one on the left) ...

**Comment by micahosborne** [comment]
Definitely needed!
