### ISSUE TITLE
incorrect screen area

### ISSUE THREAD

**Issue by XueqiangDong** [micahosborne/gSnap#16]
This is an amazing app!
but the working area is not detected correctlly when you move the application panel to the bottom.
So if you starting edit the layout you will have no chance to save except hard reboot you system.
check the screenshot below: (I use dash-to-panel to move the panel to the bottom)

![incorrect area](https://user-images.githubusercontent.com/30762236/131264342-86f4e721-b316-4932-bb9b-c0f8880144e8.png)

**Comment by micahosborne** [comment]
Yeah i think there is a better way to get the screen area, but i'm not currently sure how to do this.  I think g-Tile might have it somewhere in its code.

**Comment by XueqiangDong** [comment]
https://github.com/sunwxg/gnome-shell-extension-arrangeWindows
This extensition can detect the aera correctlly, not sure if there are some sample code you can use

**Comment by meronz** [comment]
I will work on it.

**Comment by micahosborne** [comment]
Thanks @meronz !

**Comment by meronz** [comment]
So what happened is that basically, while trying to get this to work, I implemented multiple monitors support. It's working but I need to test it more... Are you ok with a fairly consistent PR? I moved a bit of code in different files etc.

**Comment by micahosborne** [comment]
Yes, all is well.  When i wrote this i was moving fast, so I jumbled a lot together, any organization of things is appreciated.
