### ISSUE TITLE
No "Edit Layout" Button

### ISSUE THREAD

**Issue by rockschtar** [micahosborne/gSnap#22]
Installed from the Gnome Extensions Page (Version 6), but I can't edit any of the layouts. There is no "Edit Layout" Button in den configuration dialog. (Ubuntu 21.10)

![image](https://user-images.githubusercontent.com/87191/152042021-c5044a59-45fc-4b6e-a3db-90f47380e5dd.png)

**Comment by meronz** [comment]
You can edit layouts from the tray icon :)

**Comment by rockschtar** [comment]
> You can edit layouts from the tray icon :)

Oh! Thanks for the hint. I read the documentation and thought the button should be in the Gnome Extensions settings. Thanks again.
